//action类型定义
export const LOGIN_AUTHOR = "LOGIN_AUTHOR";
export const LOGIN_AUTHOR_COMPLETE = 'LOGIN_AUTHOR_COMPLETE';
export const LOGIN_REFRESH_TOKEN = "LOGIN_REFRESH_TOKEN";
export const LOGIN_REFRESH_TOKEN_COMPLETE = 'LOGIN_REFRESH_TOKEN_COMPLETE';
export const TOKEN_UPDATED = "TOKEN_UPDATED";
export const GET_NEARBY_BUILDLIST = 'GET_NEARBY_BUILDLIST'