//action类型定义
export const LOGIN_AUTHOR = "LOGIN_AUTHOR";
export const LOGIN_AUTHOR_COMPLETE = 'LOGIN_AUTHOR_COMPLETE';
export const LOGIN_REFRESH_TOKEN = "LOGIN_REFRESH_TOKEN";
export const LOGIN_REFRESH_TOKEN_COMPLETE = 'LOGIN_REFRESH_TOKEN_COMPLETE';
export const TOKEN_UPDATED = "TOKEN_UPDATED";

//获取评论列表
export const GET_COMMENT_LIST = 'GET_COMMENT_LIST';
export const GET_COMMENT_LIST_COMPLETE = 'GET_COMMENT_LIST_COMPLETE'
export const SEND_COMMENT = 'SEND_COMMENT';
export const SEND_COMMENT_COMPLETE = 'SEND_COMMENT_COMPLETE';
export const GET_NEARBY_BUILDLIST = 'GET_NEARBY_BUILDLIST'
